name: CI
on: [push]
jobs:
  bq:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 14 ]
#       removed version 8 temporarily to avoid sbt-updates failing because of the latest version of LogbackVersion
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}
    - name: Run BQ Tests
      run: sbt ";project bq; +test"
  dp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 14 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - name: Run DP Tests
        run: sbt ";project dp; +Test/compile"
  gcs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 14 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - name: Run GCS Tests
        run: sbt ";project gcs; +Test/compile"
  pubsub:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 14 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - name: Run PubSub Tests
        run: sbt ";project pubsub; +Test/compile"