name: Publish Local CI
on: [push]
jobs:
  publish213:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 21 ]
      fail-fast: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
          cache: 'sbt'
      - name: Publish Local for 2.13
        run: sbt "++ 2.13.12 publishLocal"
  publish3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21]
      fail-fast: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
          cache: 'sbt'
      - name: Publish Local for 3
        run: sbt "++ 3.3.1 publishLocal"