name: Publish package
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Publish package
        run: sbt "+publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}