name: Semantic Versioning Policy Check
on: [push]
jobs:
  semvercheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 11
        cache: 'sbt'
#    - name: Run Semantic Versioning Policy Check for BQ
#      run: sbt bq/versionPolicyCheck
#    - name: Run Semantic Versioning Policy Check for DP
#      run: sbt dp/versionPolicyCheck
    - name: Run Semantic Versioning Policy Check for PUBSUB
      run: sbt pubsub/versionPolicyCheck
#    - name: Run Semantic Versioning Policy Check for GCS
#      run: sbt gcs/versionPolicyCheck
